spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/pazytoluu/MicroService-commandes-produits
          search-paths: https://github.com/pazytoluu/MicroService-commandes-produits/condig-server.yml
server:
  port: 8888
